export default {
  BGOtpScreen: require('./BGOtpScreen.png'),
  WelcomeStepOne: require('./WelcomeStepOne.png'),
  WelcomeStepTwo: require('./WelcomeStepTwo.png'),
  WelcomeStepThree: require('./WelcomeStepThree.png'),
  LoginSuccess: require('./LoginSuccess.png'),
  HomeScreenBG: require('./HomeScreenBG.png'),
  Order: require('./Order.png'),
  History: require('./History.png'),
  News: require('./news.png'),
  emptyStore: require('./emptyStore.png'),
  BGStoreDetailScreen: require('./BGStoreDetailScreen.png'),
  noImageStore: require('./noImageStore.png'),
  mockImage: require('./mockImage.png'),
  emptyProduct: require('./emptyProduct.png'),
  timer: require('./timer.png'),
  bottomSlip: require('./bottomSlip.png'),
  emptyGift: require('./emptyGift.png'),
  bottomInvoice: require('./bottomInvoice.png'),
  CancelImage: require('./CancelImage.png'),
  iconSpecialRequest: require('./iconSpecialRequest.png'),
  emptyList: require('./emptyList.png'),
};
