export default {
  flagTH: require('./flagTH.png'),
  close: require('./iconClose.png'),
  HomeActive: require('./HomeActive.png'),
  HistoryInactive: require('./HistoryInActive.png'),
  OrderInactive: require('./OrderInActive.png'),
  ProfileInactive: require('./ProfileInActive.png'),
  NotificationInactive: require('./NotificationInActive.png'),
  backIcon: require('./BackIcon.png'),
  search: require('./search.png'),
  cart: require('./cart.png'),
  promoIcon: require('./promoIcon.png'),
  iconAdd: require('./iconAdd.png'),
  iconMinus: require('./iconMinus.png'),
  cartFill: require('./cartFill.png'),
  promotionDetail: require('./promotionDetail.png'),
  bin: require('./bin.png'),
  iconAddWhite: require('./iconAddWhite.png'),
  iconMinusWhite: require('./iconMinusWhite.png'),
  iconCheck: require('./iconCheck.png'),
  iconCollapse: require('./iconCollapse.png'),
};
