export default {
  flagTH: require('./flagTH.png'),
  close: require('./iconClose.png'),
  HomeActive: require('./HomeActive.png'),
  HistoryInactive: require('./HistoryInActive.png'),
  OrderInactive: require('./OrderInActive.png'),
  ProfileInactive: require('./ProfileInActive.png'),
  NotificationInactive: require('./NotificationInActive.png'),
  backIcon: require('./BackIcon.png'),
  search: require('./search.png'),
  cart: require('./cart.png'),
  promoIcon: require('./promoIcon.png'),
  iconAdd: require('./iconAdd.png'),
  iconMinus: require('./iconMinus.png'),
};
