export const REJECT_STATUS = [
  'REJECT_ORDER',
  'COMPANY_CANCEL_ORDER',
  'SALE_CANCEL_ORDER',
  'SHOPAPP_CANCEL_ORDER',
];
export const OPEN_STATUS = ['OPEN_ORDER', 'IN_DELIVERY', 'DELIVERY_SUCCESS'];
export const WAIT_CONFIRM_STATUS = ['WAIT_CONFIRM_ORDER', 'CONFIRM_ORDER'];
